apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: painel-umb-storage
  namespace: embasa-umb
  labels:
    app: painel-umb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
